services:
  - type: web
    name: sile-inat-api
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn 'app:create_app()'"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: FLASK_ENV
        value: production
      - key: LLM_API_KEY
        sync: false
